# to configure see https://pre-commit.com/#install
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
