# Default values for hpcc-azurelfile.
common:
  mountPrefix: "/var/lib/HPCCSystems"

planes:
- name: dali
  subPath: dalistorage
  size: 1Gi
  labels: [ "dali" ]
  #sku: "Standard_LRS"
- name: dll
  subPath: queries # cannot currently be changed
  size: 1Gi
  labels: [ "dll" ]
  rwmany: true
  #sku: "Standard_LRS"
- name: sasha
  subPath: sasha
  size: 1Gi
  rwmany: true
  labels: [ "sasha" ]
  #sku: "Standard_LRS"