name: generate terraform docs
on:
  push:
    branches: [main]
    paths:
      - "**.tf"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          output-file: Terraform.md
          output-method: inject
          git-push: "true"
